export {default as checkInput} from "./checkInput.js"
export {default as checkOptions} from "./checkOptions.js"
export {default as checkMatch} from "./checkMatch.js"
export {default as checkTask} from "./checkTask.js"
export {default as findRightAnswers} from "./findRightAnswers.js"